package org.medistor.x_rays;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-05-16T22:52:37.206-04:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "XrayStorageService", 
                  wsdlLocation = "classpath:wsdl/FileUploadService.wsdl",
                  targetNamespace = "http://mediStor.org/x-rays") 
public class XrayStorageService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mediStor.org/x-rays", "XrayStorageService");
    public final static QName XRayStorageSOAP = new QName("http://mediStor.org/x-rays", "xRayStorageSOAP");
    static {
        URL url = XrayStorageService.class.getClassLoader().getResource("wsdl/FileUploadService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(XrayStorageService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/FileUploadService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public XrayStorageService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XrayStorageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XrayStorageService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public XrayStorageService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public XrayStorageService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public XrayStorageService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns XRayStorage
     */
    @WebEndpoint(name = "xRayStorageSOAP")
    public XRayStorage getXRayStorageSOAP() {
        return super.getPort(XRayStorageSOAP, XRayStorage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XRayStorage
     */
    @WebEndpoint(name = "xRayStorageSOAP")
    public XRayStorage getXRayStorageSOAP(WebServiceFeature... features) {
        return super.getPort(XRayStorageSOAP, XRayStorage.class, features);
    }

}
