package org.medistor.x_rays;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-05-16T22:52:37.179-04:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://mediStor.org/x-rays", name = "xRayStorage")
@XmlSeeAlso({org.medistor.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface XRayStorage {

    @WebMethod
    @WebResult(name = "success", targetNamespace = "", partName = "success")
    public boolean store(
        @WebParam(partName = "record", name = "xRay", targetNamespace = "http://mediStor.org/types/")
        org.medistor.types.XRay record
    );
}
